package part2Project;

import java.io.*;

public class PLYWriter
{
	public static void writeFile(ArgumentParser arg, HalfEdgeScheme hes) throws Exception
	{
		int vertices = hes.numVertices();
		int edges = hes.numEdges();
		
		StringBuffer b = new StringBuffer("");
		
		
		for(int i=0; i<vertices; i++)
		{
			b.append(hes.getVertex(i).toString() + "\n");
		}
		
		for(int i=0; i<edges; i++)
		{
			HalfEdge e = hes.getHalfEdge(i);
			if(!e.face().printed)
			{
				b.append(e.face().toString(e) + "\n");
				e.face().printed = true;
			}
		}
		
//		for(int i=0; i<faces; i++)
//		{
//			out.write(hes.getFace(i).toString() + "\n");
//		}
		
		BufferedWriter out = new BufferedWriter(new FileWriter(arg.getOutputFile()));
		
		int faces = Face.numFaces;
		out.write(header(vertices, faces, arg));
		out.write(b.toString());
		
		out.close();
	}
	
	private static String header(int vertices, int faces, ArgumentParser arg)
	{
		return new String("" +
				"ply\n" +
				"format ascii 1.0\n" +
				"comment Generated by Daniel Bates's Part II Project\n" +
				"comment Using "+(arg.isAdaptive()?"":"non-")+"adaptive algorithm\n" +
				"comment Subdivision steps: " + arg.getNumSteps() + "\n" +
				"comment Degree of smoothness: " + arg.getDegree() + "\n" +
				"element vertex " + vertices + "\n" +
				"property float32 x\n" +
				"property float32 y\n" +
				"property float32 z\n" +
				"element face " + faces + "\n" +
				"property list uint8 int32 vertex_index\n" +
				"end_header\n");
	}
}
